export { CartPage } from './CartPage'
export { CategoryPage } from './CategoryPage'
export { Homepage } from './Homepage'
export { ProductListPage } from './ProductListPage'
export { ProductPage } from './ProductPage'
export { UploadPage } from './UploadPage'
export { CheckOutPage } from './CheckOutPage'
